# Generated by Django 5.0.6 on 2024-07-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is Test Description ljkjbdg jhdgkjbsf kjsgkh,df ekhlhg ethgs etjwht'),
            preserve_default=False,
        ),
    ]
