# Generated by Django 5.0.6 on 2024-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
