# Generated by Django 5.0.6 on 2024-07-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
