# Generated by Django 5.0.6 on 2024-07-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
