# Generated by Django 5.0.6 on 2024-07-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_order_being_delivered_order_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
